spring:
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistance:
          validation:
            mode:none
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/dbjwt
    username: postgres
    password: postgres
